### ISSUE TITLE
privacy

### ISSUE THREAD

**Issue by StinkyMint** [PlayboyGorilla/maxwave#1]
please doing  that we have posibble changing this in interface to self ip. static ip not secure for privacy. You add static IP 1.1.1.1

MaxwaveUtils.smali

.field public static final LOCAL_ADDR:Ljava/lang/String; = "1.1.1.1"

**Comment by PlayboyGorilla** [comment]
1.1.1.1 is a public IP address. We understand it's inappropriate to let a VPN interface have it. But could you elaborate on how it affects privacy?

> please doing that we have posibble changing this in interface to self ip. static ip not secure for privacy. You add static IP 1.1.1.1
> 
> MaxwaveUtils.smali
> 
> .field public static final LOCAL_ADDR:Ljava/lang/String; = "1.1.1.1"

**Comment by PlayboyGorilla** [comment]
The issue has been fixed by [Maxwave Proxifier for Android v1.3.15](https://github.com/PlayboyGorilla/maxwave/releases/tag/MaxwaveProxifier_for_Android_v1.3.15)

**Comment by StinkyMint** [comment]
@PlayboyGorilla
don't work new mapping, or i don't thing how use this update "new IP assignment scheme"

"But could you elaborate on how it affects privacy?"
Canvas Signature my Browser + public ip = simple identification people.

If i will use two accounts in twitter for comment, Elon musk find that i same people and ban two account.
![Screenshot](https://user-images.githubusercontent.com/94304471/214051317-3bb8a87f-80aa-4c05-b16e-cb6688771a9c.jpg)

**Comment by PlayboyGorilla** [comment]
@StinkyMint  Note that 1.1.1.1 will not be seen by anyone on the Internet. It is strictly used on your device only. When your data packets reach the Internet, their source address will be your Internet address that you acquire from your ISP. 1.1.1.1 will be not seen by Elon Musk.

As for the WebRTC leak test, my guess is, whatever test app is used, it acquires the local address of VPN interface, which in older versions of Maxwave Proxifier is 1.1.1.1 and assumes it will be used as a public address. This is wrong and will never happen in reality.

Rest assured, the information leak does not happen, even with the 1.1.1.1.
